### ISSUE TITLE
ffmpeg cannot load any data from camera

### ISSUE THREAD

**Issue by pabumake** [kopiro/homebridge-tapo-camera#34] opened 2022-01-29 23:13 UTC
Hey,

i just tried to add my C200 Camera to homebridge with your plugin. 

I just can't get any video feed or preview images. Fun Fact, I also tried it with the homebridge homebridge-camera-ffmpeg v3.1.4 wich result in nearly the same error messages.

Maybe its the underlying ffmpeg plugin that has some errors, but im no programmer.

Things checked:
Camera Feed works with VLC,
Camera Feed works with iSpyConnect

Conf Used:

```yaml
{
    "platform": "TAPO-CAMERA",
    "cameras": [
        {
            "name": "Frontkamera",
            "ipAddress": "[HOSTIP]",
            "password": "[UltraSecretPassword]",
            "streamPassword": "[Password]",
            "streamUser": "[USER]",
            "pullInterval": 60000,
            "debug": true,
            "disableStreaming": false,
            "disablePrivacyAccessory": false,
            "disableAlarmAccessory": true,
            "disableMotionAccessory": true,
            "lowQuality": false
        }
    ]
}
```

Error Log:
```ps1
[1/29/2022, 11:57:54 PM] [TAPO-CAMERA] [Frontkamera] Identify requested
[1/29/2022, 11:57:55 PM] [TAPO-CAMERA] [Frontkamera] Snapshot requested: 1280 x 720
[1/29/2022, 11:57:55 PM] [TAPO-CAMERA] [Frontkamera] Snapshot command: ffmpeg -i rtsp://[USER]:[Password]@[HOSTIP]:554/stream1 -frames:v 1 -f image2 - -hide_banner -loglevel error
[1/29/2022, 11:57:55 PM] [TAPO-CAMERA] [Frontkamera] [Snapshot] rtsp://[USER]:[Password]@[HOSTIP]:554/stream1: Protocol not found
[1/29/2022, 11:57:55 PM] [TAPO-CAMERA] [Frontkamera] [Snapshot] Did you mean file:rtsp://[USER]:[Password]@[HOSTIP]:554/stream1?
[1/29/2022, 11:57:55 PM] [TAPO-CAMERA] [Frontkamera] Fetching snapshot took 0.016 seconds.
[1/29/2022, 11:57:55 PM] [TAPO-CAMERA] [Frontkamera] Failed to fetch snapshot.
[Frontkamera BCB2] Snapshot request handler provided empty image buffer!
[1/29/2022, 11:58:01 PM] [TAPO-CAMERA] [Frontkamera] Snapshot requested: 1280 x 720
[1/29/2022, 11:58:01 PM] [TAPO-CAMERA] [Frontkamera] Snapshot command: ffmpeg -i rtsp://[USER]:[Password]@[HOSTIP]:554/stream1 -frames:v 1 -f image2 - -hide_banner -loglevel error
[1/29/2022, 11:58:01 PM] [TAPO-CAMERA] [Frontkamera] [Snapshot] rtsp://[USER]:[Password]@[HOSTIP]:554/stream1: Protocol not found
[1/29/2022, 11:58:01 PM] [TAPO-CAMERA] [Frontkamera] [Snapshot] Did you mean file:rtsp://[USER]:[Password]@[HOSTIP]:554/stream1?
[1/29/2022, 11:58:01 PM] [TAPO-CAMERA] [Frontkamera] Fetching snapshot took 0.014 seconds.
[1/29/2022, 11:58:01 PM] [TAPO-CAMERA] [Frontkamera] Failed to fetch snapshot.
[Frontkamera BCB2] Snapshot request handler provided empty image buffer!
[1/29/2022, 11:58:04 PM] [TAPO-CAMERA] [Frontkamera] Video stream requested: 1280 x 720, 30 fps, 299 kbps
[1/29/2022, 11:58:04 PM] [TAPO-CAMERA] [Frontkamera] Starting video stream: native x native, native fps, ??? kbps (AAC-eld)
[1/29/2022, 11:58:04 PM] [TAPO-CAMERA] [Frontkamera] Stream command: ffmpeg -i rtsp://[USER]:[Password]@[HOSTIP]:554/stream1 -an -sn -dn -codec:v copy -pix_fmt yuv420p -color_range mpeg -f rawvideo -payload_type 99 -ssrc 14137963 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params h3FbofzW/QYXcFKVyqZLnWYEDda4cVIJaxbPSeMD srtp://192.168.0.84:50047?rtcpport=50047&pkt_size=1316 -vn -sn -dn -codec:a libfdk_aac -profile:a aac_eld -flags +global_header -f null -ar 16k -b:a 24k -ac 1 -payload_type 110 -ssrc 16624691 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params dszR8VVVFN3s3KhLCwQwjoW+K0kcb2224op/3PAV srtp://192.168.0.84:60145?rtcpport=60145&pkt_size=188 -loglevel level+verbose -progress pipe:1
[1/29/2022, 11:58:04 PM] [TAPO-CAMERA] [Frontkamera] [info] ffmpeg version 4.1.6 Copyright (c) 2000-2020 the FFmpeg developers
[1/29/2022, 11:58:04 PM] [TAPO-CAMERA] [Frontkamera] [info]   built with gcc 7.5.0 (GCC)
[1/29/2022, 11:58:04 PM] [TAPO-CAMERA] [Frontkamera] [info]   configuration: --prefix=/usr --incdir='${prefix}/include/ffmpeg' --arch=i686 --target-os=linux --cross-prefix=/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu- --enable-cross-compile --enable-optimizations --enable-pic --enable-gpl --enable-shared --disable-static --disable-stripping --enable-version3 --enable-encoders --enable-pthreads --disable-protocols --disable-protocol=rtp --enable-protocol=file --enable-protocol=pipe --disable-muxer=image2 --disable-muxer=image2pipe --disable-swscale-alpha --disable-ffplay --disable-ffprobe --disable-doc --disable-devices --disable-bzlib --disable-altivec --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libmp3lame --disable-vaapi --disable-cuvid --disable-nvenc --disable-decoder=amrnb --disable-decoder=ac3 --disable-decoder=ac3_fixed --disable-encoder=zmbv --disable-encoder=dca --disable-decoder=dca --disable-encoder=ac3 --disable-encoder=ac3_fixed --disable-encoder=eac3 --disable-decoder=eac3 --disable-encoder=truehd --disable-decoder=truehd --disable-encoder=hevc_vaapi --disable-decoder=hevc --disable-muxer=hevc --disable-demuxer=hevc --disable-parser=hevc --disable-bsf=hevc_mp4toannexb --x86asmexe=yasm --cc=/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-wrap-gcc --enable-yasm --enable-libx264 --enable-encoder=libx264
[1/29/2022, 11:58:04 PM] [TAPO-CAMERA] [Frontkamera] [info]   libavutil      56. 22.100 / 56. 22.100
[1/29/2022, 11:58:04 PM] [TAPO-CAMERA] [Frontkamera] [info]   libavcodec     58. 35.100 / 58. 35.100
[1/29/2022, 11:58:04 PM] [TAPO-CAMERA] [Frontkamera] [info]   libavformat    58. 20.100 / 58. 20.100
[1/29/2022, 11:58:04 PM] [TAPO-CAMERA] [Frontkamera] [info]   libavdevice    58.  5.100 / 58.  5.100
[1/29/2022, 11:58:04 PM] [TAPO-CAMERA] [Frontkamera] [info]   libavfilter     7. 40.101 /  7. 40.101
[1/29/2022, 11:58:04 PM] [TAPO-CAMERA] [Frontkamera] [info]   libswscale      5.  3.100 /  5.  3.100
[1/29/2022, 11:58:04 PM] [TAPO-CAMERA] [Frontkamera] [info]   libswresample   3.  3.100 /  3.  3.100
[1/29/2022, 11:58:04 PM] [TAPO-CAMERA] [Frontkamera] [info]   libpostproc    55.  3.100 / 55.  3.100
[1/29/2022, 11:58:04 PM] [TAPO-CAMERA] [Frontkamera] [error] Unrecognized option 'srtp_out_suite'.
[1/29/2022, 11:58:04 PM] [TAPO-CAMERA] [Frontkamera] [fatal] Error splitting the argument list: Option not found
[1/29/2022, 11:58:04 PM] [TAPO-CAMERA] [Frontkamera] FFmpeg exited with code: 1 and signal: null (Error)
[1/29/2022, 11:58:04 PM] [TAPO-CAMERA] [Frontkamera] Stopped video stream.
[1/29/2022, 11:58:23 PM] [TAPO-CAMERA] [Frontkamera] Snapshot requested: 1280 x 720
[1/29/2022, 11:58:23 PM] [TAPO-CAMERA] [Frontkamera] Snapshot command: ffmpeg -i rtsp://[USER]:[Password]@[HOSTIP]:554/stream1 -frames:v 1 -f image2 - -hide_banner -loglevel error
[1/29/2022, 11:58:23 PM] [TAPO-CAMERA] [Frontkamera] [Snapshot] rtsp://[USER]:[Password]@[HOSTIP]:554/stream1: Protocol not found
[1/29/2022, 11:58:23 PM] [TAPO-CAMERA] [Frontkamera] [Snapshot] Did you mean file:rtsp://[USER]:[Password]@[HOSTIP]:554/stream1?
[1/29/2022, 11:58:23 PM] [TAPO-CAMERA] [Frontkamera] Fetching snapshot took 0.018 seconds.
[1/29/2022, 11:58:23 PM] [TAPO-CAMERA] [Frontkamera] Failed to fetch snapshot.
[Frontkamera BCB2] Snapshot request handler provided empty image buffer!
[1/29/2022, 11:58:33 PM] [TAPO-CAMERA] [Frontkamera] Snapshot requested: 1280 x 720
[1/29/2022, 11:58:33 PM] [TAPO-CAMERA] [Frontkamera] Snapshot command: ffmpeg -i rtsp://[USER]:[Password]@[HOSTIP]:554/stream1 -frames:v 1 -f image2 - -hide_banner -loglevel error
[1/29/2022, 11:58:33 PM] [TAPO-CAMERA] [Frontkamera] [Snapshot] rtsp://[USER]:[Password]@[HOSTIP]:554/stream1: Protocol not found
[1/29/2022, 11:58:33 PM] [TAPO-CAMERA] [Frontkamera] [Snapshot] Did you mean file:rtsp://[USER]:[Password]@[HOSTIP]:554/stream1?
[1/29/2022, 11:58:33 PM] [TAPO-CAMERA] [Frontkamera] Fetching snapshot took 0.015 seconds.
[1/29/2022, 11:58:33 PM] [TAPO-CAMERA] [Frontkamera] Failed to fetch snapshot.
[Frontkamera BCB2] Snapshot request handler provided empty image buffer!
[1/29/2022, 11:58:53 PM] [TAPO-CAMERA] [Frontkamera] Snapshot requested: 1280 x 720
[1/29/2022, 11:58:53 PM] [TAPO-CAMERA] [Frontkamera] Snapshot command: ffmpeg -i rtsp://[USER]:[Password]@[HOSTIP]:554/stream1 -frames:v 1 -f image2 - -hide_banner -loglevel error
[1/29/2022, 11:58:53 PM] [TAPO-CAMERA] [Frontkamera] [Snapshot] rtsp://[USER]:[Password]@[HOSTIP]:554/stream1: Protocol not found
[1/29/2022, 11:58:53 PM] [TAPO-CAMERA] [Frontkamera] [Snapshot] Did you mean file:rtsp://[USER]:[Password]@[HOSTIP]:554/stream1?
[1/29/2022, 11:58:53 PM] [TAPO-CAMERA] [Frontkamera] Fetching snapshot took 0.015 seconds.
[1/29/2022, 11:58:53 PM] [TAPO-CAMERA] [Frontkamera] Failed to fetch snapshot.
[Frontkamera BCB2] Snapshot request handler provided empty image buffer!
```

**Comment by kopiro** [comment] 2022-02-07 10:45
hello, I've received many report very similar to this, I'll try to look into, thanks

**Comment by superhardi** [comment] 2022-02-28 00:29
Hello, i get error [aq] FFmpeg process creation failed: spawn ffmpeg ENOENT
How i can fix this?

**Comment by 1aranzant** [comment] 2022-05-27 11:14
Hey! I'm getting the following issues:

`[5/27/2022, 1:08:23 PM] [tapo-camera] [Tapo] Failed to fetch snapshot.
[Tapo 2148] Snapshot request handler provided empty image buffer!
[5/27/2022, 1:09:01 PM] [tapo-camera] [Tapo] Starting video stream: native x native, native fps, ??? kbps (AAC-eld)
[5/27/2022, 1:09:01 PM] [tapo-camera] [Tapo] FFmpeg exited with code: 1 and signal: null (Error)
[5/27/2022, 1:09:01 PM] [tapo-camera] [Tapo] Stopped video stream.
[5/27/2022, 1:11:10 PM] [tapo-camera] [Tapo] Failed to fetch snapshot.
[Tapo 2148] Snapshot request handler provided empty image buffer!`

**Comment by kopiro** [comment] 2022-07-23 09:16
Duplicate of https://github.com/kopiro/homebridge-tapo-camera/issues/28

**Closed by kopiro** 2022-07-23 09:16 UTC
