### ISSUE TITLE
FFmpeg exited with code: 1 and signal: null (Error).

### ISSUE THREAD

**Issue by DevDurs** [kopiro/homebridge-tapo-camera#29] opened 2022-01-04 20:10 UTC
Stream functions once perfectly fine, but reconnecting either causes exits or major delays reconnecting of upwards of 1 minute.

Logs attached below.

[04/01/2022, 20:03:54] [TAPO-CAMERA] [Living Room] Stopped video stream.
[04/01/2022, 20:03:57] [TAPO-CAMERA] [Living Room] Starting video stream: native x native, native fps, ??? kbps (AAC-eld)
[04/01/2022, 20:04:28] [TAPO-CAMERA] [Living Room] Starting video stream: native x native, native fps, ??? kbps (AAC-eld)
[04/01/2022, 20:04:28] [TAPO-CAMERA] [Living Room] FFmpeg exited with code: 1 and signal: null (Error)
[04/01/2022, 20:04:28] [TAPO-CAMERA] [Living Room] Stopped video stream.
[04/01/2022, 20:04:34] [TAPO-CAMERA] [Living Room] Starting video stream: native x native, native fps, ??? kbps (AAC-eld)
[04/01/2022, 20:04:34] [TAPO-CAMERA] [Living Room] FFmpeg exited with code: 1 and signal: null (Error)
[04/01/2022, 20:04:34] [TAPO-CAMERA] [Living Room] Stopped video stream.
[04/01/2022, 20:04:57] [TAPO-CAMERA] [Living Room] Stopped video stream.
[04/01/2022, 20:05:17] [TAPO-CAMERA] [Living Room] Starting video stream: native x native, native fps, ??? kbps (AAC-eld)
[04/01/2022, 20:05:18] [TAPO-CAMERA] [Living Room] Failed to fetch snapshot.
[Living Room CA62] Snapshot request handler provided empty image buffer!
[04/01/2022, 20:05:18] [TAPO-CAMERA] [Living Room] Stopped video stream.
[04/01/2022, 20:05:19] [TAPO-CAMERA] [Living Room] Starting video stream: native x native, native fps, ??? kbps (AAC-eld)
[04/01/2022, 20:05:20] [TAPO-CAMERA] [Living Room] FFmpeg exited with code: 1 and signal: null (Error)
[04/01/2022, 20:05:20] [TAPO-CAMERA] [Living Room] Stopped video stream.

**Comment by kopiro** [comment] 2022-07-23 09:14
Duplicate of https://github.com/kopiro/homebridge-tapo-camera/issues/28

**Closed by kopiro** 2022-07-23 09:14 UTC
