### ISSUE TITLE
aq] FFmpeg process creation failed: spawn ffmpeg ENOENT

### ISSUE THREAD

**Issue by superhardi** [kopiro/homebridge-tapo-camera#49] opened 2022-03-01 23:50 UTC
[3/2/2022, 9:50:06 AM] [homebridge-tapo-camera] [Выход] FFmpeg process creation failed: spawn ffmpeg ENOENT
[Выход 63D1] Snapshot request handler provided empty image buffer!
[3/2/2022, 9:50:06 AM] [homebridge-tapo-camera] [aq] FFmpeg process creation failed: spawn ffmpeg ENOENT
[aq DA12] Snapshot request handler provided empty image buffer!
[3/2/2022, 9:50:12 AM] [homebridge-tapo-camera] [aq] Starting video stream: native x native, native fps, ??? kbps (AAC-eld)
[3/2/2022, 9:50:12 AM] [homebridge-tapo-camera] [aq] FFmpeg process creation failed: spawn ffmpeg ENOENT
[3/2/2022, 9:50:12 AM] [homebridge-tapo-camera] [aq] Stopped video stream.

**Comment by superhardi** [comment] 2022-03-02 06:58
Alredy install this https://github.com/Sunoo/homebridge-camera-ffmpeg#readme

ср, 2 мар. 2022 г. в 16:16, eiryu ***@***.***>:

**Comment by kopiro** [comment] 2022-07-23 09:15
Duplicate of https://github.com/kopiro/homebridge-tapo-camera/issues/28

**Closed by kopiro** 2022-07-23 09:15 UTC
Labels: bug
